### PR TITLE
Adding missing rst for new files

### PR DESCRIPTION
**Pull request by PaulWessel**
Also adding images and logos.

### CODE REVIEW

**Comment by PaulWessel** [comment]
Should mention that I get this build error:

```
reading sources... [100%] index
/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/remote-datasets/docs/index.rst:13: ERROR: Invalid directive argument: argument must be 1 or 4 (xs sm md lg) values, and each value should be either auto or an integer from 1 to 12
```

Maybe @seisman knows that to do?

**Review by Esteban82 — APPROVED** [review]
I think that they are ok. I make a commit to delete extra white space and fix a typo.

**Comment by seisman** [comment]
I see more warnings:
```
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-edefl.rst:: WARNING: image file not readable: _static/GMT_earth_edefl.jpg
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-faaerror.rst:: WARNING: duplicate label tbl-earth_faa, other instance in /Users/seisman/OSS/gmt/remote-datasets/docs/earth-faa.rst
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-faaerror.rst:: WARNING: image file not readable: _static/GMT_earth_faaerror.jpg
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-gebco.rst:: WARNING: image file not readable: _static/GMT_earth_gebco.jpg
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-mag.rst:: WARNING: image file not readable: _static/GMT_earth_mag.jpg
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-mdt.rst:: WARNING: image file not readable: _static/GMT_earth_mdt.jpg
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-ndefl.rst:2: WARNING: Title underline too short.

IGPP Earth South-North Deflections
--------------------------------
/Users/seisman/OSS/gmt/remote-datasets/docs/earth-ndefl.rst:: WARNING: image file not readable: _static/GMT_earth_ndefl.jpg
/Users/seisman/OSS/gmt/remote-datasets/docs/index.rst:13: ERROR: Invalid directive argument: argument must be 1 or 4 (xs sm md lg) values, and each value should be either auto or an integer from 1 to 12
/Users/seisman/OSS/gmt/remote-datasets/docs/index.rst:137: WARNING: duplicated entry found in toctree: earth-faa
/Users/seisman/OSS/gmt/remote-datasets/docs/index.rst:137: WARNING: duplicated entry found in toctree: earth-gebco
/Users/seisman/OSS/gmt/remote-datasets/docs/index.rst:137: WARNING: duplicated entry found in toctree: earth-mask
/Users/seisman/OSS/gmt/remote-datasets/docs/index.rst:137: WARNING: duplicated entry found in toctree: earth-relief
/Users/seisman/OSS/gmt/remote-datasets/docs/index.rst:137: WARNING: duplicated entry found in toctree: earth-daynight
/Users/seisman/OSS/gmt/remote-datasets/docs/venus-relief.rst:2: WARNING: Title underline too short.

NASA Venus Relief
----------------
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/seisman/OSS/gmt/remote-datasets/docs/earth-ndefl.rst: WARNING: document isn't included in any toctree
/Users/seisman/OSS/gmt/remote-datasets/docs/mars-relief.rst: WARNING: document isn't included in any toctree
/Users/seisman/OSS/gmt/remote-datasets/docs/mercury-relief.rst: WARNING: document isn't included in any toctree
/Users/seisman/OSS/gmt/remote-datasets/docs/moon-relief.rst: WARNING: document isn't included in any toctree
/Users/seisman/OSS/gmt/remote-datasets/docs/pluto-relief.rst: WARNING: document isn't included in any toctree
/Users/seisman/OSS/gmt/remote-datasets/docs/venus-relief.rst: WARNING: document isn't included in any toctree
```

**Comment by PaulWessel** [comment]
I think I got split across two PRs... If #101 is approved then this one should have fewer issues?

**Comment by PaulWessel** [comment]
Now I only get

`/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/remote-datasets/docs/index.rst:13: ERROR: Invalid directive argument: argument must be 1 or 4 (xs sm md lg) values, and each value should be either auto or an integer from 1 to 12`

Not sure what the args to grid: means.

**Comment by seisman** [comment]
> Now I only get
> 
> `/Users/pwessel/UH/RESEARCH/CVSPROJECTS/GMTdev/remote-datasets/docs/index.rst:13: ERROR: Invalid directive argument: argument must be 1 or 4 (xs sm md lg) values, and each value should be either auto or an integer from 1 to 12`
> 
> Not sure what the args to grid: means.

Similar to my changes in https://github.com/GenericMappingTools/remote-datasets/pull/101/commits/6b49a29096291e6000075fa1c7b6429132de6502, be careful with the indents.

**Comment by PaulWessel** [comment]
I tried different spaces etc but cannot get it to work.

**Comment by seisman** [comment]
> I tried different spaces etc but cannot get it to work.

I've fixed it, now the only warning is:
```
remote-datasets/docs/index.rst:: WARNING: image file not readable: _static/GMT_earth_mag4km_thumbnail.jpg
```

**Comment by PaulWessel** [comment]
That should just be mag, not mag4k.

**Comment by Esteban82** [comment]
I have a doubt. Why the mars relief is credit to the NASA while the others planets relief (like moon) to the USGS? 

From the recipe, the source seems to be USGS.

`# SRC_FILE=https://planetarymaps.usgs.gov/mosaic/Mars/HRSC_MOLA_Blend/Mars_HRSC_MOLA_BlendDEM_Global_200mp_v2.tif`

**Comment by PaulWessel** [comment]
Well, NASA collected the data I think but sometimes they both contribute to the final product. @WalterHFSmith might know what we should do, say both logos.

**Pull request merged**
