### PR TITLE
Use Thumbnails for the front page

### PR DESCRIPTION
**Pull request by Esteban82**
I add the thumbnails of the currents images.

I also modified the script to create those maps and the index.rst to have 3 columns (instead of 2).

By error I add again the file GMT_earth_wdmam.jpg. This will not generate any problem

### CODE REVIEW

**Comment by seisman** [comment]
> the index.rst to have 3 columns (instead of 2).

You forgot to make the change?

**Comment by Esteban82** [comment]
> You forgot to make the change?

Yes, I did. I just make a new commit.

**Comment by seisman** [comment]
**Preview**: https://remote-datasets--95.org.readthedocs.build/en/95/

Looks good.

Two thoughts:

1. Remove the "Remote Datasets" heading, which seems unnecessary
2. Decrease the font size of the title.

**Comment by Esteban82** [comment]
I remove the heading.
I don't know how to decrease the font size.

Should I remove the word "global" for the data sets? I think is not important (and for some sets it is not true).

**Comment by PaulWessel** [comment]
yes, the global is a bit silly and as you say, sometimes wrong. Is there a similar table for the planets?

**Comment by seisman** [comment]
> I don't know how to decrease the font size.

I can help with it, but better to do it in a separate PR.

**Comment by Esteban82** [comment]
> Is there a similar table for the planets?

No, we have to add it. And we also have to make the `planet-relief.rst`.

**Comment by Esteban82** [comment]
> yes, the global is a bit silly and as you say

Removed.

**Review by seisman — APPROVED** [review]
Looks good to me.

**Pull request merged**
