### PR TITLE
Change images names

### PR DESCRIPTION
**Pull request by Esteban82**
This PR is only for changing the name of the maps. They now use the name corresponding to the grid from which they originate.

### CODE REVIEW

**Comment by seisman** [comment]
Instead of `GMT_relief.jpg`, I think we should use `GMT_earth_relief.jpg`, as we will have more datasets like `moon_relief`.

**Comment by Esteban82** [comment]
> Instead of `GMT_relief.jpg`, I think we should use `GMT_earth_relief.jpg`, as we will have more datasets like `moon_relief`.

Well, in this case, all maps should start with `GMT_earth_`.

**Comment by PaulWessel** [comment]
I agree with @seisman here. Simpler to do GMT_<dataset>.jpg, no?

**Comment by Esteban82** [comment]
Ok. I will update the names.

**Comment by Esteban82** [comment]
I just rename all the figures.  Ready to be approved.

**Comment by Esteban82** [comment]
I should also modify the scripts and the readme. But I prefer to do it in another PR.

**Comment by Esteban82** [comment]
When this PR is approved and merge, I will make another one for #88.

**Review by PaulWessel — APPROVED** [review]

**Pull request merged**
