### PR TITLE
Homogenize maps

### PR DESCRIPTION
**Pull request by Esteban82**
See #88 for details.

I homogenize the scripts. I made some minors modifications for the previous scripts and I made a generic script for the rest.
I notice that the WDMAM map has different colors. It seems that now uses a different CPT.

The only map lacking is day-night. I can adapt the ex 52 from gallery or just make the day version with the generic script (that's why I added WIP).

Is it possible that the figures are bigger (in KB)? Why is that? The dimensions are the same. What should I do? Use an smaller width, like 10 cm?

### CODE REVIEW

**Comment by Esteban82** [comment]
> Is it possible that the figures are bigger (in KB)? Why is that? The dimensions are the same. What should I do? Use an smaller width, like 10 cm?

Now most of maps are smaller thanks to the bot.

**Comment by Esteban82** [comment]
I add the maps for day-night.

BTW, It seems that the bot re-compress `GMT_earth_wdmam.jpg`.

**Comment by seisman** [comment]
Some images are still above 500 KB. Please note that all these images will be shown on the front page of the Remote Dataset sites. It means visiting the page need to download more than 5 MB images.

So the smaller these images, the better.

**Comment by PaulWessel** [comment]
I guess this makes sense - I never worry about bandwidth but obviously that is not the case for most.

**Comment by Esteban82** [comment]
Ok. I will try with to get smaller figures. Which should be the size for each figure?

**Comment by Esteban82** [comment]
I set the map width to 7.5 cm (instead of 15 cm) for most of the figures. I didn't do it for the maps with legends (age and mask).

The total size (after compression) is 1.38 MB for the 10 maps.

**Comment by seisman** [comment]
Looks good to me: https://remote-datasets--91.org.readthedocs.build/en/91/index.html

**Review by PaulWessel — APPROVED** [review]

**Pull request merged**
